export type DriverInfo = {
  doc_number: string;
  no_kart: string;
  tarikh_sodor: string;
  code_meli: string;
  name: string;
  family: string;
  father_name: string;
  birth_date: string;
  nove_ranandeh: string;
  shomare_gavahinameh: string;
  somare_bime: string;
  is_active: string;
  tarikh_payan_etebar: string;
  shahr_mahal_sokonat: string;
  mahale_daryaft: string;
  comments: string;
  state_code: string;
  tahsilat_code: string;
  salamat_date: string;
  salamat_no: string;
  shobe: string;
  gozarname_no: string;
  shomare_shenasname: string;
  certificate_end_date: string;
};
export type InqueryData = {
  nationalId: string;
  cardNo: string;
  companyCode: string;
};
export type FreighterInfo = {
  doc_number: string;
  no_kart: string;
  shenaseh_khodro: string;
  shomare_serial_plaque: string;
  nove_plaque: string;
  plq1: string;
  plq2: string;
  plq3: string;
  is_active_code: string;
  sal_sakht: string;
  system_code: string;
  type_code: string;
  zarfiat: string;
  Tedad_mehvar: string;
  tarikh_sodor: string;
  mahale_daryaft_code: string;
  nove_vasile: string;
  nove_navgan_mosaferi_code: string;
  naja_id: string;
  moa_date: string;
  NATIONAL_ID: string;
  NAME_MALEK: string;
  SHENASE_MELI: string;
  tarikh_payan_etebar: string;
  TARIKH_MOAYENE: string;
};
export type CompanyType = {
  results: [
    {
      objectId: string;
      updatedAt: string;
      createdAt: string;
      CODE: string;
      COMPANY_TYPE_CODE: string;
      ACTIVITY_TYPE_CODE: string;
      STATUS: string;
      OSTAN_CODE: string;
      GENER_KIND: string;
      LAST_NAME: string;
      ADDRESSC: string;
      COMPANY_BAR_RESPONSIBILITY: [string];
      CELLPHONE: string;
      NATIONALID: string;
      FIRST_NAME: string;
      NAME: string;
      TRANSPORT_KIND_CODE: [string];
      MALEKIAT_TYPE: string;
      LISENCE_END_DATE: {};
      NATIONAL_CODE: string;
      CITY_PLACE_CODE: string;
      LISENCE_DATE: {};
      KIND_ORG_CODE: string;
      REGISTER_DATE: {};
      WORK_PHONE: string;
      MOTHER_CMP_OSTAN_CODE: string;
      TECHNICALS: [string];
    }
  ];
};
export type CompaniesAllVehicleType = {
  objectId: string;
  createdAt: string;
  updatedAt: string;
  CODE: string;
  INTELLIGENCE_CARD: string;
  PELAK2: string;
  PELAK1: string;
  PELAK3: string;
  SERIAL_MASHIN: string;
  OWNER_KIND: string;
  BELONG_START_DATE: { iso: string; __type: string };
  BELONG_END_DATE: { iso: string; __type: string };
  OSTAN_CODE: string;
  OSTAN_NAME: string;
  NAME: string;
  REQUEST_KIND: string;
  NATIONALID: string;
};
export type CompanyAgreementsTypes = {
  objectId: string;
  updatedAt: string;
  path: string;
  createdAt: string;
  TYPEAGREEMENT: string;
  START_DATE: { iso: string; __type: string };
  END_DATE: { iso: string; __type: string };
  STATUS: string;
  MotherCode: string;
  CODE_COMPANY_BASE: string;
  CODE_COMPANY_SUBS: string;
  CODE_PLACE_MOTHER: string;
  CODE_PLACE_BASE: string;
  CODE_PLACE_SUBS: string;
};
